owner: OleVikNTNU
repo: Uptime

sites:
  - name: Innsida
    url: https://i.ntnu.no/
  - name: Temaside for saksbehandling
    url: https://i.ntnu.no/saksbehandling
  - name: Arkivplan
    url: https://ntnu.no/arkivplan
  - name: Arkivplan / Automatisering
    url: https://www.ntnu.no/arkivplan/automatisering
  - name: Arkivplan GitLab
    url: https://ntnu-doku.gitlab.io/arkivplan
  - name: Arkivplan GitLab / Automatisering
    url: https://ntnu-doku.gitlab.io/arkivplan/automatisering
  - name: Avdeling for dokumentasjonsforvaltning
    url: https://www.ntnu.no/adm/doku

status-website:
  baseUrl: /Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Oppetid for enkelte nettadresser ved NTNU"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
